name: 'Setup project'
description: 'Sets up project and its dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    - shell: bash
      run: |
        corepack enable
        corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate
        pnpm install --frozen-lockfile
